# Generated by Django 4.2.1 on 2023-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="gjzpCookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=200)),
                (
                    "TimeStamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
            ],
        ),
    ]
